/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SculpturesRouteImport } from './routes/sculptures'
import { Route as MemorialsRouteImport } from './routes/memorials'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CanvasPrintsRouteImport } from './routes/canvas-prints'
import { Route as AcrylicPrintsRouteImport } from './routes/acrylic-prints'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SculpturesRoute = SculpturesRouteImport.update({
  id: '/sculptures',
  path: '/sculptures',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialsRoute = MemorialsRouteImport.update({
  id: '/memorials',
  path: '/memorials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasPrintsRoute = CanvasPrintsRouteImport.update({
  id: '/canvas-prints',
  path: '/canvas-prints',
  getParentRoute: () => rootRouteImport,
} as any)
const AcrylicPrintsRoute = AcrylicPrintsRouteImport.update({
  id: '/acrylic-prints',
  path: '/acrylic-prints',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic-prints': typeof AcrylicPrintsRoute
  '/canvas-prints': typeof CanvasPrintsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRouteWithChildren
  '/weddings': typeof WeddingsRoute
  '/shop/$productId': typeof ShopProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic-prints': typeof AcrylicPrintsRoute
  '/canvas-prints': typeof CanvasPrintsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRouteWithChildren
  '/weddings': typeof WeddingsRoute
  '/shop/$productId': typeof ShopProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic-prints': typeof AcrylicPrintsRoute
  '/canvas-prints': typeof CanvasPrintsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRouteWithChildren
  '/weddings': typeof WeddingsRoute
  '/shop/$productId': typeof ShopProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acrylic-prints'
    | '/canvas-prints'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/weddings'
    | '/shop/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acrylic-prints'
    | '/canvas-prints'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/weddings'
    | '/shop/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acrylic-prints'
    | '/canvas-prints'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/weddings'
    | '/shop/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcrylicPrintsRoute: typeof AcrylicPrintsRoute
  CanvasPrintsRoute: typeof CanvasPrintsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  MemorialsRoute: typeof MemorialsRoute
  SculpturesRoute: typeof SculpturesRoute
  ShopRoute: typeof ShopRouteWithChildren
  WeddingsRoute: typeof WeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sculptures': {
      id: '/sculptures'
      path: '/sculptures'
      fullPath: '/sculptures'
      preLoaderRoute: typeof SculpturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorials': {
      id: '/memorials'
      path: '/memorials'
      fullPath: '/memorials'
      preLoaderRoute: typeof MemorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-prints': {
      id: '/canvas-prints'
      path: '/canvas-prints'
      fullPath: '/canvas-prints'
      preLoaderRoute: typeof CanvasPrintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acrylic-prints': {
      id: '/acrylic-prints'
      path: '/acrylic-prints'
      fullPath: '/acrylic-prints'
      preLoaderRoute: typeof AcrylicPrintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcrylicPrintsRoute: AcrylicPrintsRoute,
  CanvasPrintsRoute: CanvasPrintsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  MemorialsRoute: MemorialsRoute,
  SculpturesRoute: SculpturesRoute,
  ShopRoute: ShopRouteWithChildren,
  WeddingsRoute: WeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
