/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SculpturesRouteImport } from './routes/sculptures'
import { Route as MemorialsRouteImport } from './routes/memorials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CanvasPrintsRouteImport } from './routes/canvas-prints'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AcrylicPrintsRouteImport } from './routes/acrylic-prints'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as MemorialCreateRouteImport } from './routes/memorial.create'
import { Route as MemorialSlugRouteImport } from './routes/memorial.$slug'
import { Route as MemorialSlugEditRouteImport } from './routes/memorial.$slug.edit'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SculpturesRoute = SculpturesRouteImport.update({
  id: '/sculptures',
  path: '/sculptures',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialsRoute = MemorialsRouteImport.update({
  id: '/memorials',
  path: '/memorials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasPrintsRoute = CanvasPrintsRouteImport.update({
  id: '/canvas-prints',
  path: '/canvas-prints',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AcrylicPrintsRoute = AcrylicPrintsRouteImport.update({
  id: '/acrylic-prints',
  path: '/acrylic-prints',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const MemorialCreateRoute = MemorialCreateRouteImport.update({
  id: '/memorial/create',
  path: '/memorial/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialSlugRoute = MemorialSlugRouteImport.update({
  id: '/memorial/$slug',
  path: '/memorial/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialSlugEditRoute = MemorialSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MemorialSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic-prints': typeof AcrylicPrintsRoute
  '/affiliates': typeof AffiliatesRoute
  '/canvas-prints': typeof CanvasPrintsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/weddings': typeof WeddingsRoute
  '/memorial/$slug': typeof MemorialSlugRouteWithChildren
  '/memorial/create': typeof MemorialCreateRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/memorial/$slug/edit': typeof MemorialSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic-prints': typeof AcrylicPrintsRoute
  '/affiliates': typeof AffiliatesRoute
  '/canvas-prints': typeof CanvasPrintsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/weddings': typeof WeddingsRoute
  '/memorial/$slug': typeof MemorialSlugRouteWithChildren
  '/memorial/create': typeof MemorialCreateRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/memorial/$slug/edit': typeof MemorialSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic-prints': typeof AcrylicPrintsRoute
  '/affiliates': typeof AffiliatesRoute
  '/canvas-prints': typeof CanvasPrintsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/weddings': typeof WeddingsRoute
  '/memorial/$slug': typeof MemorialSlugRouteWithChildren
  '/memorial/create': typeof MemorialCreateRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/memorial/$slug/edit': typeof MemorialSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acrylic-prints'
    | '/affiliates'
    | '/canvas-prints'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/signup'
    | '/weddings'
    | '/memorial/$slug'
    | '/memorial/create'
    | '/shop/$productId'
    | '/memorial/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acrylic-prints'
    | '/affiliates'
    | '/canvas-prints'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/signup'
    | '/weddings'
    | '/memorial/$slug'
    | '/memorial/create'
    | '/shop/$productId'
    | '/memorial/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acrylic-prints'
    | '/affiliates'
    | '/canvas-prints'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/signup'
    | '/weddings'
    | '/memorial/$slug'
    | '/memorial/create'
    | '/shop/$productId'
    | '/memorial/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcrylicPrintsRoute: typeof AcrylicPrintsRoute
  AffiliatesRoute: typeof AffiliatesRoute
  CanvasPrintsRoute: typeof CanvasPrintsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MemorialsRoute: typeof MemorialsRoute
  SculpturesRoute: typeof SculpturesRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignupRoute: typeof SignupRoute
  WeddingsRoute: typeof WeddingsRoute
  MemorialSlugRoute: typeof MemorialSlugRouteWithChildren
  MemorialCreateRoute: typeof MemorialCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sculptures': {
      id: '/sculptures'
      path: '/sculptures'
      fullPath: '/sculptures'
      preLoaderRoute: typeof SculpturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorials': {
      id: '/memorials'
      path: '/memorials'
      fullPath: '/memorials'
      preLoaderRoute: typeof MemorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-prints': {
      id: '/canvas-prints'
      path: '/canvas-prints'
      fullPath: '/canvas-prints'
      preLoaderRoute: typeof CanvasPrintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acrylic-prints': {
      id: '/acrylic-prints'
      path: '/acrylic-prints'
      fullPath: '/acrylic-prints'
      preLoaderRoute: typeof AcrylicPrintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/memorial/create': {
      id: '/memorial/create'
      path: '/memorial/create'
      fullPath: '/memorial/create'
      preLoaderRoute: typeof MemorialCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial/$slug': {
      id: '/memorial/$slug'
      path: '/memorial/$slug'
      fullPath: '/memorial/$slug'
      preLoaderRoute: typeof MemorialSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial/$slug/edit': {
      id: '/memorial/$slug/edit'
      path: '/edit'
      fullPath: '/memorial/$slug/edit'
      preLoaderRoute: typeof MemorialSlugEditRouteImport
      parentRoute: typeof MemorialSlugRoute
    }
  }
}

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface MemorialSlugRouteChildren {
  MemorialSlugEditRoute: typeof MemorialSlugEditRoute
}

const MemorialSlugRouteChildren: MemorialSlugRouteChildren = {
  MemorialSlugEditRoute: MemorialSlugEditRoute,
}

const MemorialSlugRouteWithChildren = MemorialSlugRoute._addFileChildren(
  MemorialSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcrylicPrintsRoute: AcrylicPrintsRoute,
  AffiliatesRoute: AffiliatesRoute,
  CanvasPrintsRoute: CanvasPrintsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MemorialsRoute: MemorialsRoute,
  SculpturesRoute: SculpturesRoute,
  ShopRoute: ShopRouteWithChildren,
  SignupRoute: SignupRoute,
  WeddingsRoute: WeddingsRoute,
  MemorialSlugRoute: MemorialSlugRouteWithChildren,
  MemorialCreateRoute: MemorialCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
